# Generated by Django 2.2 on 2022-03-22 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=128, unique=True)),
                ('startDate', models.DateTimeField(default=datetime.datetime(2022, 3, 22, 15, 16, 49, 734050, tzinfo=utc))),
                ('description', models.CharField(default=' ', max_length=500)),
            ],
        ),
    ]
